### ISSUE TITLE
Two crash reports using .combine

### ISSUE THREAD

**Issue by truemagic-coder** [anaisbetts/SassAndCoffee#18]
Currently only using .combine for javascript files - these errors have been generated multiple times since installing about a week ago on the web server using SassandCoffee 1.0 on ASP.NET MVC3 on IIS 7.5 on Windows Server 2008 R2 x64.

---

Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException
Stack:
   at System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   at System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type, Boolean)
   at SassAndCoffee.Core.JS.CreateJavascriptCompiler()
   at SassAndCoffee.Core.JavascriptBasedCompiler.<.cctor>b__0()
   at System.Threading.ExecutionContext.runTryCode(System.Object)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

---

An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/1/ROOT

Process ID: 9300

Exception: System.Reflection.TargetInvocationException

Message: Exception has been thrown by the target of an invocation.

StackTrace:    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at SassAndCoffee.Core.JS.CreateJavascriptCompiler()
   at SassAndCoffee.Core.JavascriptBasedCompiler.<.cctor>b__0()
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: System.AccessViolationException

Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

StackTrace:    at v8.HandleScope.{ctor}(HandleScope\* )
   at NativeV8ScriptCompiler.{ctor}(NativeV8ScriptCompiler\* )
   at V8Bridge.V8ScriptCompiler..ctor()

**Comment by anaisbetts** [comment]
Are these issues 100% reproducible? Without at least line numbers /
offsets or a crash dump, it's going to be very hard for me to figure
out what's going on...

## 

Paul Betts paul@paulbetts.org

On Wed, Jul 27, 2011 at 10:08 PM, bevanhunt
reply@reply.github.com
wrote:

**Comment by kevinrjones** [comment]
I'm seeing something similar. I have SassAndCoffee installed but I'm not writing any coffee or SASS at the moment. I get this:

An unhandled exception occurred and the process was terminated.

Application ID: /LM/W3SVC/1/ROOT

Process ID: 4908

Exception: System.Reflection.TargetInvocationException

Message: Exception has been thrown by the target of an invocation.

StackTrace:    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipVisibilityChecks, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at SassAndCoffee.Core.JS.CreateJavascriptCompiler()
   at SassAndCoffee.Core.JavascriptBasedCompiler.<.cctor>b__0()
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: System.AccessViolationException

Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

StackTrace:    at v8.HandleScope.{ctor}(HandleScope\* )
   at NativeV8ScriptCompiler.{ctor}(NativeV8ScriptCompiler\* )
   at V8Bridge.V8ScriptCompiler..ctor()

I can reproduce this.

Same setup as above SassandCoffee 1.0 on ASP.NET MVC3 on IIS 7.5 on Windows Server 2008 R2 x64

**Comment by anaisbetts** [comment]
I'm working on a new release that has a new version of V8 - let me know if this still hits on that version (I'll reping this bug once it comes out)

**Comment by kogir** [comment]
Fixed in v2.0 with new JScript engine.
