### ISSUE TITLE
Avoid writing and loading V8Bridge_x86.dll to temp

### ISSUE THREAD

**Issue by friism** [anaisbetts/SassAndCoffee#25]
Looking at this code, the V8Bridge dll is loaded from resources, then written to the temp folder before being loaded with Assembly.Load(). This currently fails on AppHarbor (where I happen to work) for unknown reasons. Is there any way SassAndCoffee could just load the assembly from resource directly? I tried to poke around a little, but couldn't get it to work.

The relevant code is here:
https://github.com/xpaulbettsx/SassAndCoffee/blob/master/SassAndCoffee.Core/JavascriptInterop.cs#L168

Michael

**Comment by jgoz** [comment]
This is likely not possible, since V8Bridge is not compiled with /clr:safe and it contains a mix of native and managed code. Such assemblies can only be loaded from disk, according to [this Microsoft Connect issue](http://connect.microsoft.com/VisualStudio/feedback/details/97801/loading-mixed-assembly-with-assembly-load-byte-throw-exception-changed-behaviour).

**Comment by friism** [comment]
Got it, thanks.

**Comment by grumpydev** [comment]
@jgoz @friism would it not be possible to potentially let you override the loading of the DLL to load it from a specific location, rather than extract to temp and load it from there, so you can upload it to a directory on AppHarbor, or would that not help?

**Comment by jgoz** [comment]
It might work if the 'bin' directory was used as the extraction path and then if that fails, fall back to a Temp path.

But @friism, you indicated that LoadFile fails for unknown reasons. Can you verify whether or not the Bridge assembly can actually be extracted to a temp path? It's possible that the extraction succeeds and the LoadFile call fails if the executing AppDomain is not running in Full Trust, as you can only load unmanaged code in a Full Trust environment. Does AppHarbor run projects in Full Trust?

**Comment by friism** [comment]
I can confirm that the extraction to the temp-folder succeeds. I can also load the bytes out of the extracted file, but Assembly.Load fails for some reason.

**Comment by manadart** [comment]
I'm encountering this one too, with a published web application. I'm running under IIS6 on WS2003 SP2. 
I can see that the file is extracted to the temp path. It's spitting on Assembly.Load for me too.

**Comment by sorenbs** [comment]
Running windows 2008 IIS7 on a 32 bit EC2 instance i see the same problem. The assembly is extracted to windows/temp/ but it fails on Assembly.LoadFile. See full error below. The website is run with .NET Trust Level = full.
Further it fails to fall back to jurassic and just throws the error, causing iis to suspend the app pool.

From the comment i would guess this check in Core.JS should be inverted?
// Jurassic completely bites it on 64-bit, we just need to abort
                    if (Environment.Is64BitProcess == false) {
                        throw;
                    }

Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:

Server stack trace: 
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at SassAndCoffee.Core.JS.<.cctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   at System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value()
   at SassAndCoffee.Core.JS.CreateJavascriptCompiler()
   at SassAndCoffee.Core.JavascriptBasedCompiler.<.cctor>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.runTryCode(System.Object)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode, CleanupCode, System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
