### ISSUE TITLE
Intermittent IndexOutOfRangeException causing 100% cpu

### ISSUE THREAD

**Issue by dizzib** [anaisbetts/SassAndCoffee#50]
My server event log shows the following error after a request causes the cpu to peg at 100% requiring a kill of w3wp.exe, at which point a new w3wp.exe starts and the request completes.

Running v2.0 with file cache enabled and output cache disabled.

I've logged it here as a separate issue to aid with tracking. Hope that's ok.

Cheers!
Andy.

```
Exception information: 
Exception type: IndexOutOfRangeException 
Exception message: Index was outside the bounds of the array.
at System.Collections.Generic.Dictionary`2.Resize()
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at IronRuby.Runtime.RubyUtils.RecursionTracker.TrackObject(Object obj)
at IronRuby.Builtins.RubyArray.GetHashCode(UnaryOpStorage hashStorage, ConversionStorage`1 fixnumCast, IList self)
at Microsoft.Scripting.Interpreter.FuncCallInstruction`4.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronRuby.Runtime.EqualityComparer.System.Collections.Generic.IEqualityComparer<System.Object>.GetHashCode(Object obj)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at IronRuby.Runtime.RubyUtils.SetHashElement(RubyContext context, IDictionary`2 obj, Object key, Object value)
at IronRuby.Runtime.RubyUtils.SetHashElements(RubyContext context, Hash hash, Object[] items)
at Microsoft.Scripting.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
at IronRuby.Runtime.RubyScriptCode.Run(Scope scope, Boolean bindGlobals)
at SassAndCoffee.Ruby.Sass.SassCompiler.Initialize()
at SassAndCoffee.Ruby.Sass.SassCompiler.Compile(String path, Boolean compressed, IList`1 dependentFileList)
at SassAndCoffee.Ruby.Sass.SassCompilerContentTransform.Execute(ContentTransformState state)
at SassAndCoffee.Core.ContentPipeline.ProcessRequest(String physicalPath)
at SassAndCoffee.AspNet.PipelineHandler.ProcessRequest(HttpContext context)
at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by bstrausser** [comment]
I'm having the same issue. Any hope of a fix on this?

@dizzib How frequent was intermittent in your case?

**Comment by kogir** [comment]
I briefly looked into this long ago, and it's an IronRuby bug.  IronRuby was a cool idea, but it's no longer maintained.

**Comment by dizzib** [comment]
IIRC it happened once or twice a day.
